### ISSUE TITLE
Addon errors on init in Blender 2.82 

### ISSUE THREAD

**Issue by Anarchid** [sanguinariojoe/blender_s3o_import#6]
See https://springrts.com/phpbb/viewtopic.php?p=593826#p593826 :

```
Post by Fenlig » 28 Mar 2020, 03:56
Any luck updating this to 2.82, don't seem to want to enable for me

Code: Select all

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\s3o_import.py", line 64
    raise NameError, 'Not a Spring unit file: \'' + self.magic + '\''
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\s3o_import.py", line 64
    raise NameError, 'Not a Spring unit file: \'' + self.magic + '\''
                   ^
SyntaxError: invalid syntax
```

**Comment by sanguinariojoe** [comment]
I would say you are actually using an outdated version... Indeed, if you take a look of the failing line it is just a comment:

https://github.com/sanguinariojoe/blender_s3o_import/blob/master/s3o_import.py#L64

Many things can failed... I suggest you completely remove the module from blender, check you have the latest version (`git pull origin master`), and install again...

Please let me know!

**Comment by sanguinariojoe** [comment]
Apparently the actual reporter is not replying... I'm closing the issue... Just for the record, the original report at the forum:

https://springrts.com/phpbb/viewtopic.php?p=590923#p590923
